# do not install anything extra onto the image
language: generic

sudo: required

# use a Linux image
os: linux

# only run builds on pushes to the master branch
branches:
  only:
  - kossinator
  
before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh

#Install Editor
install:
- ./Scripts/install.sh

# Build
script:
- ./Scripts/build.sh